/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jpbonfa.vendas.view;

import br.com.jpbonfa.vendas.controller.MenuController;
import br.com.jpbonfa.vendas.model.Funcionario;
import javax.swing.JButton;
import javax.swing.JMenu;

/**
 *
 * @author joaop
 */
public class MenuView extends javax.swing.JFrame {

    private MenuController menuController = new MenuController(MenuView.this);
    private Funcionario funcionarioConectado;

    public MenuView() {
//        this.funcionarioConectado = funcionarioConectado;
        initComponents();
        setLocationRelativeTo(null);
        //   setExtendedState(MAXIMIZED_BOTH);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btClientes = new javax.swing.JButton();
        btFornecedor = new javax.swing.JButton();
        btFuncionarios = new javax.swing.JButton();
        btProdutos = new javax.swing.JButton();
        btVendas = new javax.swing.JButton();
        btCompras = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnCadastro = new javax.swing.JMenu();
        itemMnClientes = new javax.swing.JMenuItem();
        itemMnFornecedores = new javax.swing.JMenuItem();
        itemMnProdutos = new javax.swing.JMenuItem();
        itemMnFuncionarios = new javax.swing.JMenuItem();
        mnEstoque = new javax.swing.JMenu();
        itemMnControle = new javax.swing.JMenuItem();
        itemMnProdutoFalta = new javax.swing.JMenuItem();
        mnVendas = new javax.swing.JMenu();
        itemMnEfetuarVendar = new javax.swing.JMenuItem();
        mnCompras = new javax.swing.JMenu();
        itemMnEfetuarCompra = new javax.swing.JMenuItem();
        mnContas = new javax.swing.JMenu();
        itemMnContaPagar = new javax.swing.JMenuItem();
        itemMnContaReceber = new javax.swing.JMenuItem();
        mnSistemas = new javax.swing.JMenu();
        itemMnSobre = new javax.swing.JMenuItem();
        itemMnLogout = new javax.swing.JMenuItem();
        itemMnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sistema Comercial de Vendas");
        setMinimumSize(new java.awt.Dimension(1240, 660));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("USUÁRIO:");

        btClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jpbonfa/vendas/img/clientes.png"))); // NOI18N
        btClientes.setText("Clientes");
        btClientes.setMaximumSize(new java.awt.Dimension(170, 50));
        btClientes.setMinimumSize(new java.awt.Dimension(170, 50));
        btClientes.setPreferredSize(new java.awt.Dimension(170, 50));
        btClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClientesActionPerformed(evt);
            }
        });

        btFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jpbonfa/vendas/img/fornecedor.png"))); // NOI18N
        btFornecedor.setText("Fornecedor");
        btFornecedor.setMaximumSize(new java.awt.Dimension(170, 50));
        btFornecedor.setMinimumSize(new java.awt.Dimension(170, 50));
        btFornecedor.setPreferredSize(new java.awt.Dimension(170, 50));
        btFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFornecedorActionPerformed(evt);
            }
        });

        btFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jpbonfa/vendas/img/funcionario.png"))); // NOI18N
        btFuncionarios.setText("Funcionários");
        btFuncionarios.setMaximumSize(new java.awt.Dimension(170, 50));
        btFuncionarios.setMinimumSize(new java.awt.Dimension(170, 50));
        btFuncionarios.setPreferredSize(new java.awt.Dimension(170, 50));
        btFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFuncionariosActionPerformed(evt);
            }
        });

        btProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jpbonfa/vendas/img/estoque.png"))); // NOI18N
        btProdutos.setText("Produtos");
        btProdutos.setMaximumSize(new java.awt.Dimension(170, 50));
        btProdutos.setMinimumSize(new java.awt.Dimension(170, 50));
        btProdutos.setPreferredSize(new java.awt.Dimension(170, 50));
        btProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProdutosActionPerformed(evt);
            }
        });

        btVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jpbonfa/vendas/img/venda.gif"))); // NOI18N
        btVendas.setText("Vendas");
        btVendas.setMaximumSize(new java.awt.Dimension(170, 50));
        btVendas.setMinimumSize(new java.awt.Dimension(170, 50));
        btVendas.setPreferredSize(new java.awt.Dimension(170, 50));
        btVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVendasActionPerformed(evt);
            }
        });

        btCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jpbonfa/vendas/img/relatorio.png"))); // NOI18N
        btCompras.setText("Compras");
        btCompras.setMaximumSize(new java.awt.Dimension(170, 50));
        btCompras.setMinimumSize(new java.awt.Dimension(170, 50));
        btCompras.setPreferredSize(new java.awt.Dimension(170, 50));
        btCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprasActionPerformed(evt);
            }
        });

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jpbonfa/vendas/img/sair.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.setMaximumSize(new java.awt.Dimension(170, 50));
        btSair.setMinimumSize(new java.awt.Dimension(170, 50));
        btSair.setPreferredSize(new java.awt.Dimension(170, 50));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        mnCadastro.setText("Cadastro");

        itemMnClientes.setText("Clientes");
        itemMnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMnClientesActionPerformed(evt);
            }
        });
        mnCadastro.add(itemMnClientes);

        itemMnFornecedores.setText("Fornecedores");
        itemMnFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMnFornecedoresActionPerformed(evt);
            }
        });
        mnCadastro.add(itemMnFornecedores);

        itemMnProdutos.setText("Produtos");
        itemMnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMnProdutosActionPerformed(evt);
            }
        });
        mnCadastro.add(itemMnProdutos);

        itemMnFuncionarios.setText("Funcionarios");
        itemMnFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMnFuncionariosActionPerformed(evt);
            }
        });
        mnCadastro.add(itemMnFuncionarios);

        jMenuBar1.add(mnCadastro);

        mnEstoque.setText("Estoque");

        itemMnControle.setText("Controle de Estoque");
        itemMnControle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMnControleActionPerformed(evt);
            }
        });
        mnEstoque.add(itemMnControle);

        itemMnProdutoFalta.setText("Produto em Falta");
        mnEstoque.add(itemMnProdutoFalta);

        jMenuBar1.add(mnEstoque);

        mnVendas.setText("Vendas");

        itemMnEfetuarVendar.setText("Efetuar Vendas");
        itemMnEfetuarVendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMnEfetuarVendarActionPerformed(evt);
            }
        });
        mnVendas.add(itemMnEfetuarVendar);

        jMenuBar1.add(mnVendas);

        mnCompras.setText("Compras");

        itemMnEfetuarCompra.setText("Efetuar Compras");
        itemMnEfetuarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMnEfetuarCompraActionPerformed(evt);
            }
        });
        mnCompras.add(itemMnEfetuarCompra);

        jMenuBar1.add(mnCompras);

        mnContas.setText("Contas");

        itemMnContaPagar.setText("Contas a Pagar");
        itemMnContaPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMnContaPagarActionPerformed(evt);
            }
        });
        mnContas.add(itemMnContaPagar);

        itemMnContaReceber.setText("Contas a Receber");
        itemMnContaReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMnContaReceberActionPerformed(evt);
            }
        });
        mnContas.add(itemMnContaReceber);

        jMenuBar1.add(mnContas);

        mnSistemas.setText("Sistemas");

        itemMnSobre.setText("Sobre");
        mnSistemas.add(itemMnSobre);

        itemMnLogout.setText("Logout");
        itemMnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMnLogoutActionPerformed(evt);
            }
        });
        mnSistemas.add(itemMnLogout);

        itemMnSair.setText("Sair");
        mnSistemas.add(itemMnSair);

        jMenuBar1.add(mnSistemas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.menuController.acaoBotaoSair();
    }//GEN-LAST:event_btSairActionPerformed

    private void itemMnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMnLogoutActionPerformed
        this.menuController.acaoMenuLogout();
    }//GEN-LAST:event_itemMnLogoutActionPerformed

    private void btFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFuncionariosActionPerformed
        this.menuController.acaoBotaoFuncionario();
    }//GEN-LAST:event_btFuncionariosActionPerformed

    private void btFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFornecedorActionPerformed
        this.menuController.acaoBotaoFornecedor();
    }//GEN-LAST:event_btFornecedorActionPerformed

    private void btProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProdutosActionPerformed
        this.menuController.acaoBotaoProdutos();
    }//GEN-LAST:event_btProdutosActionPerformed

    private void btComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprasActionPerformed
        this.menuController.acaoBotaoCompras();
    }//GEN-LAST:event_btComprasActionPerformed

    private void btVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVendasActionPerformed
        this.menuController.acaoBotaoVendas();
    }//GEN-LAST:event_btVendasActionPerformed

    private void btClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClientesActionPerformed
        this.menuController.acaoBotaoClientes();
    }//GEN-LAST:event_btClientesActionPerformed

    private void itemMnContaPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMnContaPagarActionPerformed
        this.menuController.acaoMenuContasAPagar();

    }//GEN-LAST:event_itemMnContaPagarActionPerformed

    private void itemMnContaReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMnContaReceberActionPerformed
        this.menuController.acaoMenuContasAReceber();
    }//GEN-LAST:event_itemMnContaReceberActionPerformed

    private void itemMnControleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMnControleActionPerformed
        this.menuController.acaoMenuEstoque();
    }//GEN-LAST:event_itemMnControleActionPerformed

    private void itemMnEfetuarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMnEfetuarCompraActionPerformed
        this.menuController.acaoMenuEfetuarCompra();
    }//GEN-LAST:event_itemMnEfetuarCompraActionPerformed

    private void itemMnEfetuarVendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMnEfetuarVendarActionPerformed
        this.menuController.acaoMenuEfetuarVenda();
    }//GEN-LAST:event_itemMnEfetuarVendarActionPerformed

    private void itemMnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMnClientesActionPerformed
        this.menuController.acaoBotaoClientes();
    }//GEN-LAST:event_itemMnClientesActionPerformed

    private void itemMnFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMnFornecedoresActionPerformed
        this.menuController.acaoBotaoFornecedor();
    }//GEN-LAST:event_itemMnFornecedoresActionPerformed

    private void itemMnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMnProdutosActionPerformed
        this.menuController.acaoBotaoProdutos();
    }//GEN-LAST:event_itemMnProdutosActionPerformed

    private void itemMnFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMnFuncionariosActionPerformed
        this.menuController.acaoBotaoFuncionario();
    }//GEN-LAST:event_itemMnFuncionariosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClientes;
    private javax.swing.JButton btCompras;
    private javax.swing.JButton btFornecedor;
    private javax.swing.JButton btFuncionarios;
    private javax.swing.JButton btProdutos;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btVendas;
    private javax.swing.JMenuItem itemMnClientes;
    private javax.swing.JMenuItem itemMnContaPagar;
    private javax.swing.JMenuItem itemMnContaReceber;
    private javax.swing.JMenuItem itemMnControle;
    private javax.swing.JMenuItem itemMnEfetuarCompra;
    private javax.swing.JMenuItem itemMnEfetuarVendar;
    private javax.swing.JMenuItem itemMnFornecedores;
    private javax.swing.JMenuItem itemMnFuncionarios;
    private javax.swing.JMenuItem itemMnLogout;
    private javax.swing.JMenuItem itemMnProdutoFalta;
    private javax.swing.JMenuItem itemMnProdutos;
    private javax.swing.JMenuItem itemMnSair;
    private javax.swing.JMenuItem itemMnSobre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnCadastro;
    private javax.swing.JMenu mnCompras;
    private javax.swing.JMenu mnContas;
    private javax.swing.JMenu mnEstoque;
    private javax.swing.JMenu mnSistemas;
    private javax.swing.JMenu mnVendas;
    // End of variables declaration//GEN-END:variables

    public JButton getBtClientes() {
        return btClientes;
    }

    public void setBtClientes(JButton btClientes) {
        this.btClientes = btClientes;
    }

    public JButton getBtCompras() {
        return btCompras;
    }

    public void setBtCompras(JButton btCompras) {
        this.btCompras = btCompras;
    }

    public JButton getBtFornecedor() {
        return btFornecedor;
    }

    public void setBtFornecedor(JButton btFornecedor) {
        this.btFornecedor = btFornecedor;
    }

    public JButton getBtFuncionarios() {
        return btFuncionarios;
    }

    public void setBtFuncionarios(JButton btFuncionarios) {
        this.btFuncionarios = btFuncionarios;
    }

    public JButton getBtProdutos() {
        return btProdutos;
    }

    public void setBtProdutos(JButton btProdutos) {
        this.btProdutos = btProdutos;
    }

    public JButton getBtSair() {
        return btSair;
    }

    public void setBtSair(JButton btSair) {
        this.btSair = btSair;
    }

    public JMenu getMnCadastro() {
        return mnCadastro;
    }

    public void setMnCadastro(JMenu mnCadastro) {
        this.mnCadastro = mnCadastro;
    }

    public JMenu getMnCompras() {
        return mnCompras;
    }

    public void setMnCompras(JMenu mnCompras) {
        this.mnCompras = mnCompras;
    }

    public JMenu getMnContas() {
        return mnContas;
    }

    public void setMnContas(JMenu mnContas) {
        this.mnContas = mnContas;
    }

    public JMenu getMnEstoque() {
        return mnEstoque;
    }

    public void setMnEstoque(JMenu mnEstoque) {
        this.mnEstoque = mnEstoque;
    }

    public JMenu getMnSistemas() {
        return mnSistemas;
    }

    public void setMnSistemas(JMenu mnSistemas) {
        this.mnSistemas = mnSistemas;
    }

    public JMenu getMnVendas() {
        return mnVendas;
    }

    public void setMnVendas(JMenu mnVendas) {
        this.mnVendas = mnVendas;
    }

}
